### ISSUE TITLE
[Licensing] Add license terms for the logo reuse

### ISSUE THREAD

**Issue by Adafede** [lotusnprod/lotus-web#28]
Optionally provide the original file and/or upload it to https://commons.wikimedia.org/wiki/Main_Page

@oolonek, @mSorok Your take?

**Comment by Kohulan** [comment]
@Adafede I could give you the original PSD(Photoshop file) and High res PNG Images. The Lotus flower I drew from Scratch so we can publish it with CC-By 4.0 but I am not sure about the font used there. The font used might have a different license.

**Comment by Adafede** [comment]
Seems perfect. Do you have an svg version also? If the font is a problem, can we switch it to a non-problematic one?

@oolonek You are the artist, if I remember well you had one also, so please we wanna hear you 😄

**Comment by Kohulan** [comment]
Yes, I could generate whichever format you want. I am adding a suggestion here:
Font used here has a free commercial license: https://fontesk.com/alvarado-typeface/
![lotus-2](https://user-images.githubusercontent.com/30716951/182797899-a7d92b6d-7e28-4544-8244-943b27e53172.png)

**Comment by Kohulan** [comment]
@Adafede Could you update me regarding the logo, If you agree with this font we can stick with it.

**Comment by Adafede** [comment]
I know @oolonek has been working on one, I am not an artist at all, sadly.

I would say we can stick with it for now, see how the update goes, include what is in my branch, #7 , #25, update the data and we will have an answer by then 😜
