### ISSUE TITLE
No mongodb data

### ISSUE THREAD

**Issue by stuchalk** [lotusnprod/lotus-web#31]
After going into mongo and dropping the database NPOC2021 we get the following which indicates we have no data to reinstall.  How do we solve this?

```
> db.dropDatabase()
{ "ok" : 1 }
> exit
bye
root@54ce1f4c6c12:/mongodata# cd mongodata/NPOC2021/NPOC2021/
bash: cd: mongodata/NPOC2021/NPOC2021/: No such file or directory
root@54ce1f4c6c12:/mongodata# 
```

**Comment by Adafede** [comment]
Hi @stuchalk!

Thank you for your issue, the README was maybe not clear enough, so I added some details.
Could you try now and come back if something remains unclear?

Best,

**Comment by stuchalk** [comment]
Thanks.  That makes sense.  You can close the issue.

**Comment by Adafede** [comment]
👍🏼
