### ISSUE TITLE
Differences between relations available on Wikidata and the LOTUS web interface

### ISSUE THREAD

**Issue by maximeDelmas** [lotusnprod/lotus-web#60]
Hello,

I may have noticed some inconsistencies between the data available by SPARQL request on Wikidata and those available on the LOTUS web interface, which I understood as a mirror of what's in Wikidata.

For instance, N(6)-(1,2-dicarboxyethyl)-AMP (Q2823236) in found produced by Valsa sordida (Q7912606) and this relation is referenced by the publication Phosphoproteomic and Metabolomic Profiling Uncovers the Roles of CcPmk1 in the Pathogenicity of Cytospora chrysosperma (https://doi.org/10.1128/SPECTRUM.00176-22). However, this relation does not seems to be available on the LOTUS interface.

Is this just an update issue ?

Thanks for your help.

**Comment by Adafede** [comment]
Hi again @maximeDelmas,

As suggested in your other issue, please have a look at #59, you will probably find the answer there. If not, simply ping us 😊

**Comment by maximeDelmas** [comment]
Sorry, I think now it's clear thx a lot !
