### ISSUE TITLE
How to get all compounds from Plantae

### ISSUE THREAD

**Issue by zzzqiii** [lotusnprod/lotus-web#62]
Hi, thanks for your efforts on the valuable database.
I want to get all natural compounds found in Plantae  with information of `Chemical ontology`, `Organism taxonomy` and `smiles`, and I tried to download data from MongDB. However I found the data is not consistent with that in the Lotus website.
For example, this is the organism source for `LTS0257199`  from MongoDB and website.
![image](https://github.com/lotusnprod/lotus-web/assets/78252314/c577ed60-4aba-459f-9684-bc10fe3a5707)

![image](https://github.com/lotusnprod/lotus-web/assets/78252314/97600368-40c3-425e-9b1c-937fad816a90)
I wonder how I can get the source of organism with the same form as the website that I can clearly know its `Phylum`, `Family`, `Genus`, `Species`, etc. Can I get all these information by wikidata query? If so, how to use wiki query to get all compounds from Plantae?
Thanks!

**Comment by Adafede** [comment]
Hi,

Thank you for your report.
- First news: the mongo dump is indeed outdated. 
- Good news: there are plenty of alternatives!
  - A DOI-citable version of what you seem to look for is already available in our shared datasets hosted on Zenodo: https://zenodo.org/communities/the-lotus-initiative/?page=1&size=20 (https://zenodo.org/record/7534071 more precisely)
  - You can also achieve it using SPARQL, multiple similar example queries are available at <https://www.wikidata.org/wiki/Special:MyLanguage/Wikidata:WikiProject_Chemistry/Natural_products>

Hope this helps

**Comment by zzzqiii** [comment]
Thanks for your advice! I have found the data I need.
I have one more question. I noticed that one compound have its CAS registry number in the Lotus websit. However, I didn't find it in the metadata on Zenodo and MongDB. Is there any way that I can get the corresponding CAS number? @Adafede

**Comment by Adafede** [comment]
Hi,

I would suggest looking at https://www.wikidata.org/wiki/Wikidata:WikiProject_Chemistry_Natural_products#Which_are_the_available_referenced_structure-organism_pairs_on_Wikidata,_for_which_a_CAS_Registry_Number_is_available?_(limited_to_1mio) or https://w.wiki/75BD
