### ISSUE TITLE
Use of NPASS

### ISSUE THREAD

**Issue by alrichardbollans** [lotusnprod/lotus-web#63]
I was wondering about your use of NPASS as a data source as I've found a variety of inconsistencies with it in the past:

-  Found a few strange cases where '0' was given at the beginning of a name and should be replaced by 'No' e.g. https://bidd.group/NPASS/organism.php?org_id=NPO17300 
- Chloroquine (https://bidd.group/NPASS/compound.php?compoundID=NPC476464) is listed as derived from lots of species that I believe to be incorrect e.g. Vernonia brachycalyx, with reference https://pubmed.ncbi.nlm.nih.gov/9170288/
- Inaccuracies at the level of biological activities of compounds e.g. Ivermectin is listed as having antiplasmodial activity (https://bidd.group/NPASS/compound.php?compoundID=NPC469812) but the given references are unrelated and I'm struggling to find references that support the given values.

NPASS is listred as a source in your paper, so wondering if you had vetted these issues somehow as I also notice that the choloroquine/Vernonia brachycalyx issue isn't apparent in LOTUS

**Comment by Adafede** [comment]
Hi,

As for many sources, the choice of including them of not was based on a raw assessment of the data quality. This does not mean *all entries must be correct*.

We tried to curate semi-automatically everything we could, so some initially incorrect entries got discarded, but leftovers are absolutely possible.
All our curation steps are described in the article and available at https://github.com/lotusnprod/lotus-processor.

You are very welcome to contribute if you did spot things we overlooked. 👍🏼
