### ISSUE TITLE
Chloroquine

### ISSUE THREAD

**Issue by alrichardbollans** [lotusnprod/lotus-web#64]
In https://lotus.naturalproducts.net/compound/lotus_id/LTS0194649 LOTUS lists chloroquine as being found in Cinchona calisaya which is incorrect (the given reference doesn't say that cholorquine is present in this species). I believe this issue is also the same for Alkanna orientalis.

**Comment by Adafede** [comment]
Hi,

Thank you for reporting.
The data of the website is outdated, up-to-date versions are available on Zenodo and Wikidata directly.
Following your report, I went to https://www.wikidata.org/wiki/Q422438 and removed incorrect entries.
(see https://www.wikidata.org/w/index.php?title=Q422438&diff=1934902032&oldid=1934901839)
This way, they will not in the next version.

Thank you again! 👍🏼

**Comment by alrichardbollans** [comment]
Great! In future, I will make these edits in wikidata myself 👍
