### ISSUE TITLE
Role of WikiData in LOTUS

### ISSUE THREAD

**Issue by alrichardbollans** [lotusnprod/lotus-web#67]
I want to clarify the role of WikiData in LOTUS. Initially I thought LOTUS had curated a lot of sturcture-organism data which is then disseminated via https://lotus.naturalproducts.net and also via WikiData and that WikiData's role was simply dissemination. If this is the case, is it possible to extract only LOTUS-curated data from WikiData?

I suspect this isn't the case, as reading further the favoured approach to adding data to LOTUS is to add entries to WikiData directly. In this case, is there any distinction between LOTUS data and WikiData data?

**Comment by bjonnh** [comment]
The lotus.naturalproducts.net is just in an interface to a snapshot of lotus. It is not really maintained or updated and we do not have control over it anymore. So we cannot provide any support, changes or updates to it.

Wikidata serves as the main storage for all the data we add and curate. The advantage is that anybody can contribute and it can be used by people outside the natural products community. And it is here forever.

We are working on a new interface that you can see at https://search.nprod.net but this is still a work in progress. It is updated every night with new data from Wikidata.

If you tell us what you would like to achieve we can probably help you.

We also have a zenodo: https://zenodo.org/records/7534083   with the latest curated data from us. But this doesn't include any recent changes made directly on wikidata (which I insist once more is the place you should look to if you want the latest and freshest).


Hope it helps.

**Comment by alrichardbollans** [comment]
Thanks for the info. If LOTUS data is stored on WikiData, people can contribute new data to LOTUS by adding data on WikiData, and people can download LOTUS data by downloading portions of WikiData; then I'm not sure I fully understand what LOTUS is exactly, as I initially thought it was a distinct dataset but maybe its more a collection of tools and interfaces? 

I suppose two practical things would be (1) if there is no distinct LOTUS-curated data and one has to download data from WikiData, how reliable is WikiData? and (2) what would be the appropriate way to cite natural product data downloaded through WikiData?

**Comment by Adafede** [comment]
> Thanks for the info. If LOTUS data is stored on WikiData, people can contribute new data to LOTUS by adding data on WikiData, and people can download LOTUS data by downloading portions of WikiData; 

Yes. Yes. Yes. We want people to be able to interact with the data as much as possible without us. If you spot a mistake on a "classical NP website", you might rely on others to fix it, with the Wikidata model, you can fix it in seconds yourself. You can positively impact the quality of the data in no time and we think this makes a huge difference.

>then I'm not sure I fully understand what LOTUS is exactly, as I initially thought it was a distinct dataset but maybe its more a collection of tools and interfaces?

Yes again.
This is why we named it an _initiative_.
It certainly is not a database or a dataset only. As you said, one can consider it as a our attempt to allow access to high quality NP data for everyone.

> I suppose two practical things would be (1) if there is no distinct LOTUS-curated data and one has to download data from WikiData, how reliable is WikiData?

There are some _subtle_ differences.
 - Some datasets we curated had restrictive licenses so we cannot share them openly on Wikidata.
 - The datasets we deposit on Zenodo (https://zenodo.org/communities/the-lotus-initiative) contain additional metadata we cannot map 1 to 1 on Wikidata actually. We are working on some ways to make great improvements in this regard to happen but are not there yet.

> and (2) what would be the appropriate way to cite natural product data downloaded through WikiData?

If you made a custom SPARQL query to download your data, then share it. Eventually also freeze the results of your query and upload it to a public repository allowing to have the exact same data (see https://zenodo.org/records/6873163 for example).
If you obtained the data from Zenodo or the lotus website, the appropriate way to cite them should be included directly.
In any ways, we did not built LOTUS to get citations, so feel free to use the data even without citing us. 😊

**Comment by alrichardbollans** [comment]
This clarification is really helpful, thank you! Really appreciate the detailed response
