### ISSUE TITLE
Errors in Lotus

### ISSUE THREAD

**Issue by keepertrout** [lotusnprod/lotus-web#68]
How and where can erroneous entries in the Lotus database be reported and corrected?  For example mescaline has an entry of being reported from Echinopsis spachianus. If a person is familiar with the reference that is included, that paper specifically did not observe mescaline in this species (either in their experimental subjects or in their controls). This is only one example of erroneous data that would benefit from correction.

**Comment by Adafede** [comment]
Hi, please correct everything directly on Wikidata. (Here, https://wikidata.org/wiki/Q193140)
We did our best to avoid errors but of course many of them can be left. Thank you very much for reporting!

**Comment by keepertrout** [comment]
Thanks!

On 11/19/23, Adriano Rutz ***@***.***> wrote:
> Hi, please correct everything directly on Wikidata. (Here,
> https://wikidata.org/wiki/Q193140)
> We did our best to avoid errors but of course many of them can be left.
> Thank you very much for reporting!
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/lotusnprod/lotus-web/issues/68#issuecomment-1817909289
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Keeper Trout


"As scarce as truth is, the supply has always been in excess of the demand."
Josh Billings 1865.
